export default
  {
    "北京市": {
      "province": { "py": "beijing", "short": "bj", "pc": "北京市" },
      //"北京市": {"py": "", "short": ""}
    },
    "上海市": {
      "province": { "py": "shanghai", "short": "sh", "pc": "上海市" },
      //"上海市": {"py": "", "short": ""}
    },
    "天津市": {
      "province": { "py": "tianjin", "short": "tj", "pc": "天津市" },
      //"天津市": {"py": "", "short": ""}
    },
    "重庆市": {
      "province": { "py": "chongqing", "short": "cq", "pc": "重庆市" },
      //"重庆市": {"py": "", "short": ""}
    },
    "河北省": {
      "province": { "py": "hebei", "short": "heb", "pc": "石家庄市" },
      "石家庄市": { "py": "shijiazhuang", "short": "shijiazhuang" },
      "唐山市": { "py": "ts", "short": "ts" },
      "邯郸市": { "py": "hd", "short": "hd" },
      "邢台市": { "py": "xingtai", "short": "xingtai" },
      "保定市": { "py": "bd", "short": "bd" },
      "张家口市": { "py": "zhangjiakou", "short": "zhangjiakou" },
      "沧州市": { "py": "cangzhou", "short": "cangzhou" },
      "廊坊市": { "py": "lf", "short": "lf" },
      "衡水市": { "py": "hs", "short": "hs" },
      "承德市": { "py": "chengde", "short": "chengde" },
      "雄安市": { "py": "xiongan", "short": "xiongan" },
      "秦皇岛市": { "py": "news_hbqhd", "short": "news_hbqhd" },
      //"石家庄市": {"py": "", "short": ""},
      //"唐山市": {"py": "", "short": ""},
      //"秦皇岛市": {"py": "", "short": ""},
      //"邯郸市": {"py": "", "short": ""},
      //"邢台市": {"py": "", "short": ""},
      //"保定市": {"py": "", "short": ""},
      //"张家口市": {"py": "", "short": ""},
      //"承德市": {"py": "", "short": ""},
      //"沧州市": {"py": "", "short": ""},
      //"廊坊市": {"py": "", "short": ""},
      //"衡水市": {"py": "", "short": ""}
    },
    "山西省": {
      "province": { "py": "shanxi", "short": "shanxi", "pc": "太原市" },
      //"太原市": {"py": "", "short": ""},
      //"大同市": {"py": "", "short": ""},
      //"阳泉市": {"py": "", "short": ""},
      //"长治市": {"py": "", "short": ""},
      //"晋城市": {"py": "", "short": ""},
      //"朔州市": {"py": "", "short": ""},
      //"晋中市": {"py": "", "short": ""},
      //"运城市": {"py": "", "short": ""},
      //"忻州市": {"py": "", "short": ""},
      //"临汾市": {"py": "", "short": ""},
      //"吕梁市": {"py": "", "short": ""}
    },
    "内蒙古": {
      "province": { "py": "neimenggu", "short": "neimenggu", "pc": "呼和浩特市" },
      //"呼和浩特市": {"py": "", "short": ""},
      //"包头市": {"py": "", "short": ""},
      //"乌海市": {"py": "", "short": ""},
      //"赤峰市": {"py": "", "short": ""},
      //"通辽市": {"py": "", "short": ""},
      //"鄂尔多斯市": {"py": "", "short": ""},
      //"呼伦贝尔市": {"py": "", "short": ""},
      //"巴彦淖尔市": {"py": "", "short": ""},
      //"乌兰察布市": {"py": "", "short": ""},
      //"锡林郭勒盟": {"py": "", "short": ""},
      //"阿拉善盟": {"py": "", "short": ""},
      //"兴安盟": {"py": "", "short": ""}
    },
    "江苏省": {
      "province": { "py": "jiangsu", "short": "js", "pc": "南京市" },
      "南京市": { "py": "nj", "short": "nj" },
      "无锡市": { "py": "jswx", "short": "jswx" },
      "徐州市": { "py": "xuzhou", "short": "xuzhou" },
      "常州市": { "py": "changzhou", "short": "changzhou" },
      "苏州市": { "py": "suz", "short": "suz" },
      "南通市": { "py": "nantong", "short": "nantong" },
      "连云港市": { "py": "news_jslyg", "short": "news_jslyg" },
      "淮安市": { "py": "news_jsha", "short": "news_jsha" },
      "盐城市": { "py": "jsyc", "short": "jsyc" },
      "扬州市": { "py": "jsyz", "short": "jsyz" },
      "镇江市": { "py": "jszj", "short": "jszj" },
      "泰州市": { "py": "jstz", "short": "jstz" },
      "宿迁市": { "py": "jssq", "short": "jssq" },
      //"南京市": {"py": "", "short": ""},
      //"无锡市": {"py": "", "short": ""},
      //"徐州市": {"py": "", "short": ""},
      //"常州市": {"py": "", "short": ""},
      //"苏州市": {"py": "", "short": ""},
      //"南通市": {"py": "", "short": ""},
      //"连云港市": {"py": "", "short": ""},
      //"淮安市": {"py": "", "short": ""},
      //"盐城市": {"py": "", "short": ""},
      //"扬州市": {"py": "", "short": ""},
      //"镇江市": {"py": "", "short": ""},
      //"泰州市": {"py": "", "short": ""},
      //"宿迁市": {"py": "", "short": ""}
    },
    "安徽省": {
      "province": { "py": "anhui", "short": "anhui", "pc": "合肥市" },
      "合肥市": { "py": "hefei", "short": "ahhf" },
      //"芜湖市": {"py": "", "short": ""},
      //"蚌埠市": {"py": "", "short": ""},
      //"淮南市": {"py": "", "short": ""},
      //"马鞍山市": {"py": "", "short": ""},
      //"淮北市": {"py": "", "short": ""},
      //"铜陵市": {"py": "", "short": ""},
      //"安庆市": {"py": "", "short": ""},
      //"黄山市": {"py": "", "short": ""},
      //"滁州市": {"py": "", "short": ""},
      //"阜阳市": {"py": "", "short": ""},
      //"宿州市": {"py": "", "short": ""},
      //"巢湖市": {"py": "", "short": ""},
      //"六安市": {"py": "", "short": ""},
      //"亳州市": {"py": "", "short": ""},
      //"池州市": {"py": "", "short": ""},
      //"宣城市": {"py": "", "short": ""}
    },
    "山东省": {
      "province": { "py": "shandong", "short": "sd", "pc": "济南市" },
      "济南市": { "py": "news_sdjinan", "short": "news_sdjinan" },
      "青岛市": { "py": "news_sdqd", "short": "news_sdqd" },
      "淄博市": { "py": "sdzb", "short": "sdzb" },
      "枣庄市": { "py": "sdzz", "short": "sdzz" },
      "东营市": { "py": "sddy", "short": "sddy" },
      "烟台市": { "py": "sdyt", "short": "sdyt" },
      "潍坊市": { "py": "sdwf", "short": "sdwf" },
      "济宁市": { "py": "sdjining", "short": "sdjining" },
      "泰安市": { "py": "sdta", "short": "sdta" },
      "威海市": { "py": "sdwh", "short": "sdwh" },
      "日照市": { "py": "sdrz", "short": "sdrz" },
      "莱芜市": { "py": "sdlw", "short": "sdlw" },
      "临沂市": { "py": "sdly", "short": "sdly" },
      "德州市": { "py": "sddz", "short": "sddz" },
      "聊城市": { "py": "sdlc", "short": "sdlc" },
      "滨州市": { "py": "sdbz", "short": "sdbz" },
      "菏泽市": { "py": "sdhz", "short": "sdhz" },
      //"青岛市": {"py": "", "short": ""},
      //"淄博市": {"py": "", "short": ""},
      //"枣庄市": {"py": "", "short": ""},
      //"东营市": {"py": "", "short": ""},
      //"潍坊市": {"py": "", "short": ""},
      //"烟台市": {"py": "", "short": ""},
      //"威海市": {"py": "", "short": ""},
      //"济宁市": {"py": "", "short": ""},
      //"泰安市": {"py": "", "short": ""},
      //"日照市": {"py": "", "short": ""},
      //"莱芜市": {"py": "", "short": ""},
      //"临沂市": {"py": "", "short": ""},
      //"德州市": {"py": "", "short": ""},
      //"聊城市": {"py": "", "short": ""},
      //"滨州市": {"py": "", "short": ""},
      //"菏泽市": {"py": "", "short": ""}
    },
    "辽宁省": {
      "province": { "py": "liaoning", "short": "ln", "pc": "沈阳市" },
      //"沈阳市": {"py": "", "short": ""},
      //"大连市": {"py": "", "short": ""},
      //"鞍山市": {"py": "", "short": ""},
      //"抚顺市": {"py": "", "short": ""},
      //"本溪市": {"py": "", "short": ""},
      //"丹东市": {"py": "", "short": ""},
      //"锦州市": {"py": "", "short": ""},
      //"营口市": {"py": "", "short": ""},
      //"阜新市": {"py": "", "short": ""},
      //"辽阳市": {"py": "", "short": ""},
      //"盘锦市": {"py": "", "short": ""},
      //"铁岭市": {"py": "", "short": ""},
      //"朝阳市": {"py": "", "short": ""},
      //"葫芦岛市": {"py": "", "short": ""}
    },
    "吉林省": {
      "province": { "py": "jilin", "short": "jilin", "pc": "长春市" },
      //"长春市": {"py": "", "short": ""},
      //"吉林市": {"py": "", "short": ""},
      //"四平市": {"py": "", "short": ""},
      //"辽源市": {"py": "", "short": ""},
      //"通化市": {"py": "", "short": ""},
      //"白山市": {"py": "", "short": ""},
      //"松原市": {"py": "", "short": ""},
      //"白城市": {"py": "", "short": ""},
      //"延边州": {"py": "", "short": ""}
    },
    "黑龙江省": {
      "province": { "py": "heilongjiang", "short": "heilongjiang", "pc": "哈尔滨市" },
      //"哈尔滨市": {"py": "", "short": ""},
      //"齐齐哈尔市": {"py": "", "short": ""},
      //"鸡西市": {"py": "", "short": ""},
      //"鹤岗市": {"py": "", "short": ""},
      //"双鸭山市": {"py": "", "short": ""},
      //"大庆市": {"py": "", "short": ""},
      //"伊春市": {"py": "", "short": ""},
      //"牡丹江市": {"py": "", "short": ""},
      //"佳木斯市": {"py": "", "short": ""},
      //"七台河市": {"py": "", "short": ""},
      //"黑河市": {"py": "", "short": ""},
      //"绥化市": {"py": "", "short": ""},
      //"大兴安岭地区": {"py": "", "short": ""}
    },
    "浙江省": {
      "province": { "py": "zhejiang", "short": "zj", "pc": "杭州市" },
      "杭州市": { "py": "hangzhou", "short": "hz" },
      //"宁波市": {"py": "", "short": ""},
      //"温州市": {"py": "", "short": ""},
      //"嘉兴市": {"py": "", "short": ""},
      //"湖州市": {"py": "", "short": ""},
      //"绍兴市": {"py": "", "short": ""},
      //"金华市": {"py": "", "short": ""},
      //"衢州市": {"py": "", "short": ""},
      //"舟山市": {"py": "", "short": ""},
      //"台州市": {"py": "", "short": ""},
      //"丽水市": {"py": "", "short": ""}
    },
    "江西省": {
      "province": { "py": "jiangxi", "short": "jiangxi", "pc": "南昌市" },
      //"南昌市": {"py": "", "short": ""},
      //"景德镇市": {"py": "", "short": ""},
      //"萍乡市": {"py": "", "short": ""},
      //"九江市": {"py": "", "short": ""},
      //"新余市": {"py": "", "short": ""},
      //"鹰潭市": {"py": "", "short": ""},
      //"赣州市": {"py": "", "short": ""},
      //"吉安市": {"py": "", "short": ""},
      //"宜春市": {"py": "", "short": ""},
      //"抚州市": {"py": "", "short": ""},
      //"上饶市": {"py": "", "short": ""}
    },
    "福建省": {
      "province": { "py": "fujian", "short": "fj", "pc": "福州市" },
      "福州市": { "py": "fuzhou", "short": "fuzhou" },
      "泉州市": { "py": "quanzhou", "short": "quanzhou" },
      "厦门市": { "py": "news_fjxm", "short": "news_fjxm" },
      "莆田市": { "py": "news_fjpt", "short": "news_fjpt" },
      "三明市": { "py": "fjsm", "short": "fjsm" },
      "漳州市": { "py": "fjzz", "short": "fjzz" },
      "南平市": { "py": "fjnp", "short": "fjnp" },
      "龙岩市": { "py": "fhly", "short": "fhly" },
      "宁德市": { "py": "fjnd", "short": "fjnd" },
      //"福州市": {"py": "", "short": ""},
      //"厦门市": {"py": "", "short": ""},
      //"莆田市": {"py": "", "short": ""},
      //"三明市": {"py": "", "short": ""},
      //"泉州市": {"py": "", "short": ""},
      //"漳州市": {"py": "", "short": ""},
      //"南平市": {"py": "", "short": ""},
      //"龙岩市": {"py": "", "short": ""},
      //"宁德市": {"py": "", "short": ""}
    },
    "湖北省": {
      "province": { "py": "hubei", "short": "hb", "pc": "武汉市" },
      "武汉市": { "py": "wuhan", "short": "wuhan" },
      //"黄石市": {"py": "", "short": ""},
      //"襄樊市": {"py": "", "short": ""},
      //"十堰市": {"py": "", "short": ""},
      //"荆州市": {"py": "", "short": ""},
      //"宜昌市": {"py": "", "short": ""},
      //"荆门市": {"py": "", "short": ""},
      //"鄂州市": {"py": "", "short": ""},
      //"孝感市": {"py": "", "short": ""},
      //"黄冈市": {"py": "", "short": ""},
      //"咸宁市": {"py": "", "short": ""},
      //"随州市": {"py": "", "short": ""},
      //"恩施州": {"py": "", "short": ""},
      //"仙桃市": {"py": "", "short": ""},
      //"天门市": {"py": "", "short": ""},
      //"潜江市": {"py": "", "short": ""},
      //"神农架林区": {"py": "", "short": ""}
    },
    "湖南省": {
      "province": { "py": "hunan", "short": "hn", "pc": "长沙市" },
      "长沙市": { "py": "changsha", "short": "changsha" },
      "湘潭市": { "py": "xiangtan", "short": "xiangtan" },
      "衡阳市": { "py": "hengyang", "short": "hengyang" },
      "岳阳市": { "py": "yueyang", "short": "yueyang" },
      "常德市": { "py": "changde", "short": "changde" },
      "郴州市": { "py": "chenzhou", "short": "chenzhou" },
      "怀化市": { "py": "huaihua", "short": "huaihua" },
      "邵阳市": { "py": "shaoyang", "short": "shaoyang" },
      "娄底市": { "py": "ld", "short": "ld" },
      "株洲市": { "py": "news_hunzz", "short": "news_hunzz" },
      "张家界市": { "py": "news_hunzjj", "short": "news_hunzjj" },
      "益阳市": { "py": "hunyy", "short": "hunyy" },
      "永州市": { "py": "hunyz", "short": "hunyz" },
      "湘西市": { "py": "hunxx", "short": "hunxx" },
      //"长沙市": {"py": "", "short": ""},
      //"株洲市": {"py": "", "short": ""},
      //"湘潭市": {"py": "", "short": ""},
      //"衡阳市": {"py": "", "short": ""},
      //"邵阳市": {"py": "", "short": ""},
      //"岳阳市": {"py": "", "short": ""},
      //"常德市": {"py": "", "short": ""},
      //"张家界市": {"py": "", "short": ""},
      //"益阳市": {"py": "", "short": ""},
      //"郴州市": {"py": "", "short": ""},
      //"永州市": {"py": "", "short": ""},
      //"怀化市": {"py": "", "short": ""},
      //"娄底市": {"py": "", "short": ""},
      //"湘西州": {"py": "", "short": ""}
    },
    "河南省": {
      "province": { "py": "henan", "short": "henan", "pc": "郑州市" },
      //"郑州市": {"py": "", "short": ""},
      //"开封市": {"py": "", "short": ""},
      //"洛阳市": {"py": "", "short": ""},
      //"平顶山市": {"py": "", "short": ""},
      //"焦作市": {"py": "", "short": ""},
      //"鹤壁市": {"py": "", "short": ""},
      //"新乡市": {"py": "", "short": ""},
      //"安阳市": {"py": "", "short": ""},
      //"濮阳市": {"py": "", "short": ""},
      //"许昌市": {"py": "", "short": ""},
      //"漯河市": {"py": "", "short": ""},
      //"三门峡市": {"py": "", "short": ""},
      //"南阳市": {"py": "", "short": ""},
      //"商丘市": {"py": "", "short": ""},
      //"信阳市": {"py": "", "short": ""},
      //"周口市": {"py": "", "short": ""},
      //"驻马店市": {"py": "", "short": ""},
      //"济源市": {"py": "", "short": ""}
    },
    "广东省": {
      "province": { "py": "guangdong", "short": "gd", "pc": "广州市" },
      "广州市": { "py": "guangzhou", "short": "gz" },
      "深圳市": { "py": "shenzhen", "short": "sz" },
      //"珠海市": {"py": "", "short": ""},
      //"汕头市": {"py": "", "short": ""},
      //"韶关市": {"py": "", "short": ""},
      //"河源市": {"py": "", "short": ""},
      //"梅州市": {"py": "", "short": ""},
      //"惠州市": {"py": "", "short": ""},
      //"汕尾市": {"py": "", "short": ""},
      //"东莞市": {"py": "", "short": ""},
      //"中山市": {"py": "", "short": ""},
      //"江门市": {"py": "", "short": ""},
      //"佛山市": {"py": "", "short": ""},
      //"阳江市": {"py": "", "short": ""},
      //"湛江市": {"py": "", "short": ""},
      //"茂名市": {"py": "", "short": ""},
      //"肇庆市": {"py": "", "short": ""},
      //"清远市": {"py": "", "short": ""},
      //"潮州市": {"py": "", "short": ""},
      //"揭阳市": {"py": "", "short": ""},
      //"云浮市": {"py": "", "short": ""}
    },
    "广西": {
      "province": { "py": "guangxi", "short": "guangxi", "pc": "南宁市" },
      //"南宁市": {"py": "", "short": ""},
      //"柳州市": {"py": "", "short": ""},
      //"桂林市": {"py": "", "short": ""},
      //"梧州市": {"py": "", "short": ""},
      //"北海市": {"py": "", "short": ""},
      //"防城港市": {"py": "", "short": ""},
      //"钦州市": {"py": "", "short": ""},
      //"贵港市": {"py": "", "short": ""},
      //"玉林市": {"py": "", "short": ""},
      //"百色市": {"py": "", "short": ""},
      //"贺州市": {"py": "", "short": ""},
      //"河池市": {"py": "", "short": ""},
      //"来宾市": {"py": "", "short": ""},
      //"崇左市": {"py": "", "short": ""}
    },
    "海南省": {
      "province": { "py": "hainan", "short": "hainan", "pc": "海口市" },
      //"海口市": {"py": "", "short": ""},
      //"三亚市": {"py": "", "short": ""},
      //"五指山市": {"py": "", "short": ""},
      //"琼海市": {"py": "", "short": ""},
      //"儋州市": {"py": "", "short": ""},
      //"文昌市": {"py": "", "short": ""},
      //"万宁市": {"py": "", "short": ""},
      //"东方市": {"py": "", "short": ""},
      //"澄迈县": {"py": "", "short": ""},
      //"定安县": {"py": "", "short": ""},
      //"屯昌县": {"py": "", "short": ""},
      //"临高县": {"py": "", "short": ""},
      //"白沙黎族自治县": {"py": "", "short": ""}
    },
    "四川省": {
      "province": { "py": "sichuan", "short": "cd", "pc": "成都市" },
      "成都市": { "py": "chengdu", "short": "chengdu" },
      //"自贡市": {"py": "", "short": ""},
      //"攀枝花市": {"py": "", "short": ""},
      //"泸州市": {"py": "", "short": ""},
      //"德阳市": {"py": "", "short": ""},
      //"绵阳市": {"py": "", "short": ""},
      //"广元市": {"py": "", "short": ""},
      //"遂宁市": {"py": "", "short": ""},
      //"内江市": {"py": "", "short": ""},
      //"乐山市": {"py": "", "short": ""},
      //"南充市": {"py": "", "short": ""},
      //"宜宾市": {"py": "", "short": ""},
      //"广安市": {"py": "", "short": ""},
      //"达州市": {"py": "", "short": ""},
      //"眉山市": {"py": "", "short": ""},
      //"雅安市": {"py": "", "short": ""},
      //"巴中市": {"py": "", "short": ""},
      //"资阳市": {"py": "", "short": ""},
      //"阿坝州": {"py": "", "short": ""},
      //"甘孜州": {"py": "", "short": ""},
      //"凉山州": {"py": "", "short": ""}
    },
    "贵州省": {
      "province": { "py": "guizhou", "short": "guizhou", "pc": "贵阳市" },
      //"贵阳市": {"py": "", "short": ""},
      //"六盘水市": {"py": "", "short": ""},
      //"遵义市": {"py": "", "short": ""},
      //"安顺市": {"py": "", "short": ""},
      //"铜仁地区": {"py": "", "short": ""},
      //"毕节地区": {"py": "", "short": ""},
      //"黔西南州": {"py": "", "short": ""},
      //"黔东南州": {"py": "", "short": ""},
      //"黔南州": {"py": "", "short": ""}
    },
    "云南省": {
      "province": { "py": "yunnan", "short": "yn", "pc": "昆明市" },
      //"昆明市": {"py": "", "short": ""},
      //"曲靖市": {"py": "", "short": ""},
      //"玉溪市": {"py": "", "short": ""},
      //"保山市": {"py": "", "short": ""},
      //"昭通市": {"py": "", "short": ""},
      //"丽江市": {"py": "", "short": ""},
      //"思茅市": {"py": "", "short": ""},
      //"临沧市": {"py": "", "short": ""},
      //"文山州": {"py": "", "short": ""},
      //"红河州": {"py": "", "short": ""},
      //"西双版纳州": {"py": "", "short": ""},
      //"楚雄州": {"py": "", "short": ""},
      //"大理州": {"py": "", "short": ""},
      //"德宏州": {"py": "", "short": ""},
      //"怒江州": {"py": "", "short": ""},
      //"迪庆州": {"py": "", "short": ""},
      //"普洱市": {"py": "", "short": ""}
    },
    "西藏": {
      "province": { "py": "", "short": "", "pc": "拉萨市" },
      //"拉萨市": {"py": "", "short": ""},
      //"那曲地区": {"py": "", "short": ""},
      //"昌都地区": {"py": "", "short": ""},
      //"山南地区": {"py": "", "short": ""},
      //"日喀则地区": {"py": "", "short": ""},
      //"阿里地区": {"py": "", "short": ""},
      //"林芝地区": {"py": "", "short": ""}
    },
    "陕西省": {
      "province": { "py": "xian", "short": "xian", "pc": "西安市" },
      //"西安市": {"py": "", "short": ""},
      //"铜川市": {"py": "", "short": ""},
      //"宝鸡市": {"py": "", "short": ""},
      //"咸阳市": {"py": "", "short": ""},
      //"渭南市": {"py": "", "short": ""},
      //"延安市": {"py": "", "short": ""},
      //"汉中市": {"py": "", "short": ""},
      //"榆林市": {"py": "", "short": ""},
      //"安康市": {"py": "", "short": ""},
      //"商洛市": {"py": "", "short": ""}
    },
    "甘肃省": {
      "province": { "py": "gansu", "short": "gansu", "pc": "兰州市" },
      //"兰州市": {"py": "", "short": ""},
      //"金昌市": {"py": "", "short": ""},
      //"白银市": {"py": "", "short": ""},
      //"天水市": {"py": "", "short": ""},
      //"嘉峪关市": {"py": "", "short": ""},
      //"武威市": {"py": "", "short": ""},
      //"张掖市": {"py": "", "short": ""},
      //"平凉市": {"py": "", "short": ""},
      //"酒泉市": {"py": "", "short": ""},
      //"庆阳市": {"py": "", "short": ""},
      //"定西市": {"py": "", "short": ""},
      //"陇南市": {"py": "", "short": ""},
      //"临夏州": {"py": "", "short": ""},
      //"甘南州": {"py": "", "short": ""}
    },
    "宁夏": {
      "province": { "py": "ningxia", "short": "ningxia", "pc": "银川市" },
      //"银川市": {"py": "", "short": ""},
      //"石嘴山市": {"py": "", "short": ""},
      //"吴忠市": {"py": "", "short": ""},
      //"固原市": {"py": "", "short": ""},
      //"中卫市": {"py": "", "short": ""}
    },
    "青海省": {
      "province": { "py": "qinghai", "short": "qinghai", "pc": "西宁市" },
      //"西宁市": {"py": "", "short": ""},
      //"海东地区": {"py": "", "short": ""},
      //"海北州": {"py": "", "short": ""},
      //"黄南州": {"py": "", "short": ""},
      //"海南州": {"py": "", "short": ""},
      //"果洛州": {"py": "", "short": ""},
      //"玉树州": {"py": "", "short": ""},
      //"海西州": {"py": "", "short": ""}
    },
    "新疆": {
      "province": { "py": "", "short": "", "pc": "乌鲁木齐市" },
      //"乌鲁木齐市": {"py": "", "short": ""},
      //"克拉玛依市": {"py": "", "short": ""},
      //"吐鲁番地区": {"py": "", "short": ""},
      //"哈密地区": {"py": "", "short": ""},
      //"和田地区": {"py": "", "short": ""},
      //"阿克苏地区": {"py": "", "short": ""},
      //"喀什地区": {"py": "", "short": ""},
      //"克孜勒苏柯州": {"py": "", "short": ""},
      //"巴音郭楞州": {"py": "", "short": ""},
      //"昌吉州": {"py": "", "short": ""},
      //"博尔塔拉州": {"py": "", "short": ""},
      //"伊犁州": {"py": "", "short": ""},
      //"塔城地区": {"py": "", "short": ""},
      //"阿勒泰地区": {"py": "", "short": ""},
      //"石河子市": {"py": "", "short": ""},
      //"阿拉尔市": {"py": "", "short": ""}
    },
    "香港": {
      "province": { "py": "", "short": "", "pc": "香港" },
      //"香港": {"py": "", "short": ""}
    },
    "澳门": {
      "province": { "py": "", "short": "", "pc": "澳门" },
      //"澳门": {"py": "", "short": ""}
    },
    "台湾省": {
      "province": { "py": "", "short": "", "pc": "台北" },
      //"台北": {"py": "", "short": ""},
      //"高雄": {"py": "", "short": ""},
      //"台中": {"py": "", "short": ""},
      //"花莲": {"py": "", "short": ""},
      //"基隆": {"py": "", "short": ""},
      //"嘉义": {"py": "", "short": ""},
      //"金门": {"py": "", "short": ""},
      //"连江": {"py": "", "short": ""},
      //"苗栗": {"py": "", "short": ""},
      //"南投": {"py": "", "short": ""},
      //"澎湖": {"py": "", "short": ""},
      //"屏东": {"py": "", "short": ""},
      //"台东": {"py": "", "short": ""},
      //"台南": {"py": "", "short": ""},
      //"桃园": {"py": "", "short": ""},
      //"新竹": {"py": "", "short": ""},
      //"宜兰": {"py": "", "short": ""},
      //"云林": {"py": "", "short": ""},
      //"彰化": {"py": "", "short": ""}
    }
  }